language: java
sudo: false

jdk:
  - oraclejdk8

install:
  - cd server/sonar-web && npm install && cd ../..

script:
  - cd server/sonar-web && npm test && cd ../..
  - cd server/sonar-web && npm build && cd ../..
  - mvn verify -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
