language: java
sudo: false
install: true

jdk:
  - oraclejdk8

before_script:
  - cd server/sonar-web && npm install && cd ../..

script:
  - cd server/sonar-web && npm test && npm build && cd ../.. && mvn verify -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
